# Generated by Django 4.2.3 on 2023-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieCatalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default=None),
        ),
    ]
